120946 121156 new top design
weseek/growi-org pull request #22
Opened 2023-05-16 12:24 UTC by satof3

# 変更箇所
- Navbar
　- 項目の変更
　- デザインの調整
- トップデザイン
- オープンソースGROWIセクション（新設）
-  コミュニティサポートセクション（新設）
- トップへのスクロールボタンの廃止
- WEBフォントの追加
　- Fontawesomeのアップデート
　- Montserrat , NotoSans追加

# スクショ
## PC
<img width="721" alt="スクリーンショット 2023-05-16 21 15 59" src="https://github.com/weseek/growi-org/assets/113958844/7e221885-401d-4a50-9b44-35a0f04c1e19">
<img width="720" alt="スクリーンショット 2023-05-16 21 16 13" src="https://github.com/weseek/growi-org/assets/113958844/0e0d8d76-80c8-46a3-9cfc-382d117cd9cb">

## SP
<img width="191" alt="スクリーンショット 2023-05-16 21 16 44" src="https://github.com/weseek/growi-org/assets/113958844/57bac4a3-08cf-4ed0-85c6-a41f804d22a1">
<img width="188" alt="スクリーンショット 2023-05-16 21 16 58" src="https://github.com/weseek/growi-org/assets/113958844/f2f98a82-037a-4253-b310-a7aae990acfa">
<img width="189" alt="スクリーンショット 2023-05-16 21 17 15" src="https://github.com/weseek/growi-org/assets/113958844/1b2068e0-1544-4229-89d7-cba2924ef6d6">
<img width="188" alt="スクリーンショット 2023-05-16 21 17 27" src="https://github.com/weseek/growi-org/assets/113958844/9d6b4258-02eb-406d-bc89-26fd3cfa0640">

# 備考
- 機能セクションより下とFooterについては別タスクで処理

## デザインカンプ
- PC
- https://xd.adobe.com/view/206c0595-619a-40f4-b2eb-190bdcc30a81-753f/screen/5c586504-dc76-4898-99f4-7a03abcde2ca/
- SP
- https://xd.adobe.com/view/206c0595-619a-40f4-b2eb-190bdcc30a81-753f/screen/83a5060e-83a2-4e53-a5f4-5e63d9d17786/

2023-05-17 06:04 UTC, yuki-takei requested changes

2023-05-17 06:04 UTC, yuki-takei commented on docs/.vuepress/public/assets/images/background-abstract-left.png
容量大きいので tinypng 等通してください
そして画像は Git LFS で管理したい

2023-05-17 06:04 UTC, yuki-takei commented on docs/.vuepress/theme/styles/style.scss
> +  font-family: Noto Sans JP;
ja だけではないのでこれは元に戻す

2023-05-18 07:07 UTC, satof3 commented on docs/.vuepress/public/assets/images/background-abstract-left.png
tynypngでファイルサイズ小さくしました
Git LFS導入し、*.jpg *.png をトラッキングさせました。

2023-05-18 07:11 UTC, satof3 commented on docs/.vuepress/theme/styles/style.scss
> +  font-family: Noto Sans JP;
戻しました

2023-05-18 07:20 UTC, merged