120946 121459 new top design latter
weseek/growi-org pull request #23
Opened 2023-05-25 06:25 UTC by satof3

## 機能と特徴セクション
- .cloudと同様にBootstrapの.cardで表示
- 画像ファイルは上層のディレクトリ`screen-shot`ごと`features`と入れ替えている
## 導入のメリット
- spページの並びで記述し`order-*`でPC表示の順番を入れ替えレスポンシブ表示をしている
## .cloud CTA
- こちらも`order-*`でPC表示の順番を入れ替えレスポンシブ表示をしている
- PC横一列、タブレットボタンだけ改行、SP縦列のイメージのレスポンシブ表示
## フッター
- PC横一列 JOIN USだけ改行、SP縦列のイメージのレスポンシブ表示

## その他
- aタグのデフォルトカラーを変更
- `.btn-hexagon-angle-right`が表示されなかったので修正
- `Home.vue`内の<style>は最小限にし、cloud関連のクラスは`style.scss`へ移動

2023-05-25 09:51 UTC, yuki-takei requested changes

2023-05-25 09:51 UTC, yuki-takei commented on docs/.vuepress/theme/styles/style.scss
> +  background-color: #EFF7FC;
カラーコード直に書くのは避けたい。
bootstrap の primary/info/success を上書きするか、それ以外に用意したい場合も _variable.scss 等を用意してまとめてほしい。

2023-05-25 09:51 UTC, yuki-takei commented on docs/.vuepress/theme/styles/style.scss
> +  @media (min-width: 992px) {
この辺も bootstrap way で書けるはず

2023-05-25 09:51 UTC, yuki-takei commented on docs/ja/README.md
> +    description: 個人が持つノウハウや知識、仕事をする中で得た経験は、企業やチームとって、組織の成長に欠かせない重要な財産です。ノウハウを共有・蓄積・活用することで組織のさらなる発展へとつながります。
textlint 通したい。別途タスクを作ってブロックにしたい。

2023-05-30 06:57 UTC, satof3 commented on docs/.vuepress/theme/styles/style.scss
> +  background-color: #EFF7FC;
今のTOPページ動いてる分は_variable.scssに移行しました。

2023-05-30 07:03 UTC, satof3 commented on docs/.vuepress/theme/styles/style.scss
> +  @media (min-width: 992px) {
こちら理解できなかったので相談させてください。
`@include media-breakpoint-up(lg) {...}`
みたいに記述するのかなと解釈したのですがbootstrapのSassマップが見つからず、そのまま記載したりするとエラーに下記のドキュメントを_variables.scss _mixin.scssに入れても駄目でした。
やってること違ったら言ってください。
https://getbootstrap.jp/docs/5.0/layout/breakpoints/

2023-05-30 07:06 UTC, satof3 commented on docs/ja/README.md
> +    description: 個人が持つノウハウや知識、仕事をする中で得た経験は、企業やチームとって、組織の成長に欠かせない重要な財産です。ノウハウを共有・蓄積・活用することで組織のさらなる発展へとつながります。
タスク作成しました。
shun-mにアサイン予定です。(口頭で承諾いただきました。)
https://redmine.weseek.co.jp/issues/123168

2023-06-02 10:14 UTC, merged